### ISSUE TITLE
init_info() 里面的逻辑好像有一个问题

### ISSUE THREAD

**Issue by yuxiao-qin** [Pinming/NWPU_COVID19_AutoReport#3]
谢谢楼主的自动填报程序，今天正搜着来着就看到了这个……

我下载运行后发现一个问题。

用的是最新的 v2.1.1 版本，master branch。

在 report.py 中：
https://github.com/Pinming/NWPU_COVID19_AutoReport/blob/827037cd0274174db2fe564464f4e1714ca99f89/report.py#L82-L84

不知道最近是不是瓜大更新了，`https://yqtb.nwpu.edu.cn/wx/ry/jrsb_xs.jsp` 现在 redirect 到 `https://yqtb.nwpu.edu.cn/wx/ry/jrsb_js.jsp` 了？

<img width="1405" alt="Screen Shot 2022-05-01 at 17 44 11" src="https://user-images.githubusercontent.com/65807097/166140717-748e8949-714d-45ed-8203-8d5293807316.png">

然后我这里改了以后，下面的这里：
https://github.com/Pinming/NWPU_COVID19_AutoReport/blob/827037cd0274174db2fe564464f4e1714ca99f89/report.py#L91-L92
我需要把 index 从 [2] 改成 [1] 才能读到正确的内容。

**Comment by Pinming** [comment]
应该是您翱翔门户的身份不是学生身份？【滑稽】
看起来 `jrsb_js` 这个 `js` 后缀应该对应的是老师…… 开发的时候我自然是无法考虑这种情况的🤣也没有老师身份的账号
不过应该跳转逻辑跟学生端是差不多的吧~

**Comment by yuxiao-qin** [comment]
那是了……我当时还想了半天js和xs是啥，javascript么……😂不过好消息是后续的逻辑是一样的，现在已经愉快地常驻在我的 crontab 里面啦，谢谢作者。

**Comment by Pinming** [comment]
> 那是了……我当时还想了半天js和xs是啥，javascript么……😂不过好消息是后续的逻辑是一样的，现在已经愉快地常驻在我的 crontab 里面啦，谢谢作者。

客气了~
