### ISSUE TITLE
在测试函数时执行失败了

### ISSUE THREAD

**Issue by AceNyanner** [Pinming/NWPU_COVID19_AutoReport#4]
谢谢大佬分享。
我是一个纯小白。今天按照您的教程配置云函数，到最后测试函数时出现了执行错误的问题
![5](https://user-images.githubusercontent.com/96412087/167661861-8daabcc1-77f5-4e5b-b473-6e1971774972.png)
看日志上应该是登录成功了，但是后面的报错都看不懂QAQ
想要知道是哪儿出了问题，求指正

**Comment by Pinming** [comment]
看报错应该是地理信息匹配的问题？您填的是“在学校”或者是其他什么类别呢

**Comment by AceNyanner** [comment]
> 看报错应该是地理信息匹配的问题？您填的是“在学校”或者是其他什么类别呢

是“在学校”

**Comment by yuxiao-qin** [comment]
我之前也碰到过这个问题，你如果填报的是奇怪的地址（location.py 里面没有的）就会搜不到就会报错。

124行直接改成
```
self.szcsbm = "610116"
```
就行了。

**Comment by AceNyanner** [comment]
> 我之前也碰到过这个问题，你如果填报的是奇怪的地址（location.py 里面没有的）就会搜不到就会报错。
> 
> 124行直接改成
> 
> ```
> self.szcsbm = "610116"
> ```
> 
> 就行了。

wwww确实是这样，谢谢佬佬

**Comment by AceNyanner** [comment]
> 我之前也碰到过这个问题，你如果填报的是奇怪的地址（location.py 里面没有的）就会搜不到就会报错。
> 
> 124行直接改成
> 
> ```
> self.szcsbm = "610116"
> ```
> 
> 就行了。

wwww确实是这样，谢谢佬佬

**Comment by Pinming** [comment]
在学校的话 `szcsbm` 应该会是 `0` 的呀，方便看看您这个页面的信息吗？
https://yqtb.nwpu.edu.cn/wx/xg/yz-mobile/rzxx_list.jsp?type=xs
![image](https://user-images.githubusercontent.com/30550234/168471475-395364c7-8690-4afc-bbdd-6df482742e18.png)

**Comment by AceNyanner** [comment]
![image](https://user-images.githubusercontent.com/96412087/168473028-e5bbd77d-7454-44db-8cba-305f6e91ee42.png)
确实是在学校，按照上面那个朋友说的`szcsbm`改成`610116`就可以正常运行了

**Comment by yuxiao-qin** [comment]
> 在学校的话 szcsbm 应该会是 0 的呀，方便看看您这个页面的信息吗？
https://yqtb.nwpu.edu.cn/wx/xg/yz-mobile/rzxx_list.jsp?type=xs

我的略不一样，因为我不一定在学校哈哈哈哈，所以我会手动填一个位置
<img width="416" alt="Screen Shot 2022-05-17 at 13 44 29" src="https://user-images.githubusercontent.com/65807097/168737899-751c9f14-ed18-4420-99a1-01ca054bd4a0.png">

**Comment by Pinming** [comment]
> ![image](https://user-images.githubusercontent.com/96412087/168473028-e5bbd77d-7454-44db-8cba-305f6e91ee42.png) 确实是在学校，按照上面那个朋友说的`szcsbm`改成`610116`就可以正常运行了

好奇怪【捂脸】

**Comment by Pinming** [comment]
> > 在学校的话 szcsbm 应该会是 0 的呀，方便看看您这个页面的信息吗？
> > https://yqtb.nwpu.edu.cn/wx/xg/yz-mobile/rzxx_list.jsp?type=xs
> 
> 我的略不一样，因为我不一定在学校哈哈哈哈，所以我会手动填一个位置 <img alt="Screen Shot 2022-05-17 at 13 44 29" width="416" src="https://user-images.githubusercontent.com/65807097/168737899-751c9f14-ed18-4420-99a1-01ca054bd4a0.png">

<img width="603" alt="image" src="https://user-images.githubusercontent.com/30550234/168796193-acd05a2a-a7c0-471f-90cd-9a3e39b412fb.png">
可以麻烦您抓一下填报上去的 Form嘛，想看一下具体获取到的信息如何，个人信息及关键部分可以打码~感谢了
