### ISSUE TITLE
函数调用失败问题

### ISSUE THREAD

**Issue by bestzy6** [Pinming/NWPU_COVID19_AutoReport#5]
大佬您好，十分感谢您分享的脚本，给我带来了很大的便利。
我将您的脚本部署在腾讯云函数中，已经成功部署了半个多月，但从6月18日开始，出现了调用失败情况。
以下是错误信息：
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='uis.nwpu.edu.cn', port=443): Max retries exceeded with url: /cas/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90658b4e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))

不知是我这设置出现了问题或是其他情况，还烦请大佬解答疑惑。

**Comment by Pinming** [comment]
估计是腾讯云方面的网络问题？这个确实不太好确定。
我这边近期使用的阿里云没有出现类似问题🤔
