### ISSUE TITLE
一个可能的问题

### ISSUE THREAD

**Issue by pikcjhan** [Pinming/NWPU_COVID19_AutoReport#6]
学长好！感谢您的程序，一直以来方便了不少。
最近离校，发现了一个可能的问题，想反映一下：上一次填报为“在西安”的，会出现报错。（也可能是我操作有误）
报错信息为：
```
 "errorMessage": "list index out of range",
    "errorType": "IndexError",
    "stackTrace": [
        [
            "File \"/code/index.py\"",
            "line 12",
            "in handler",
            "yqtb.init_info()"
        ],
        [
            "File \"/code/report.py\"",
            "line 123",
            "in init_info",
            "self.szcsbm = loc_code[0]"
        ]
    ]
}
```
“在学校”和“在国内”没有类似问题。因为我（是西安本地人）的地址是确定的、所以我进行了相应的变量直接修改；考虑到可能其他人也会有类似问题，所以来反映一下。再次谢谢学长！

**Comment by Pinming** [comment]
收到，感谢反馈。
最近也有考虑到这样的问题会不会发生，看来确实存在问题，近期会排查。

**Comment by Pinming** [comment]
该问题已在 2.1.3 版本 [`ed17026`](https://github.com/Pinming/NWPU_COVID19_AutoReport/commit/ed17026066926ea9576055f7be8e9fa6e7426404) 中修复。
